# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-03 05:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Undecided')], default='N', max_length=1)),
                ('comment', models.TextField(blank=True, default='Leave your Comment', null=True)),
                ('submit', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('accNo', models.TextField(blank=True, default=None, null=True)),
                ('pubNo', models.TextField(blank=True, default=None, null=True)),
                ('complink', models.TextField(blank=True, default=None, null=True)),
                ('content', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalresult', models.BooleanField(default=False)),
                ('data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='summary',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Topic'),
        ),
        migrations.AddField(
            model_name='curation',
            name='data_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Dataset'),
        ),
        migrations.AddField(
            model_name='curation',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Topic'),
        ),
        migrations.AddField(
            model_name='curation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
