# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='highlihgt',
            field=models.CharField(default='', max_length=300),
        ),
    ]
