# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-19 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_dataset_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='complink',
            new_name='highlight',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='content',
            new_name='keywords',
        ),
    ]
