# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-21 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20170721_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curation',
            name='result',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
