# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-21 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_auto_20170721_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curation',
            name='comment',
            field=models.TextField(blank=True, default='No comment', null=True),
        ),
    ]
