# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-21 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_auto_20170721_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curation',
            name='comment',
            field=models.TextField(blank=True, default='Comment', null=True),
        ),
    ]
