# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-21 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20170721_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curation',
            name='result',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Undecided')], max_length=1),
        ),
    ]
