# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-24 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_auto_20170721_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='accNo',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='complink',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='pubNo',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='title',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
