# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_auto_20170725_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curation',
            name='result',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Undecided')], default='N', max_length=1),
        ),
    ]
