# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-26 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_auto_20170725_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curation',
            name='comment',
            field=models.TextField(blank=True, default='Leave your Comment', null=True),
        ),
    ]
